<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DescripcionParametricaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('pp_descripcion_parametricas')->insert([

            [
                'codigo' => 'USD VENTA',
                'descripcion' => 'DOLAR VENTA',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'USD COMPRA',
                'descripcion' => 'DOLAR COMPRA',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'BS',
                'descripcion' => 'BOLIVIANOS',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'EUR',
                'descripcion' => 'EURO',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'JPY',
                'descripcion' => 'YEN',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'ARS',
                'descripcion' => 'PESO',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'AUD',
                'descripcion' => 'DÓLAR',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'BRL',
                'descripcion' => 'REAL',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'CAD',
                'descripcion' => 'DÓLAR',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'CLP',
                'descripcion' => 'PESO',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'COP',
                'descripcion' => 'PESO',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'KRW',
                'descripcion' => 'WON',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'DKK',
                'descripcion' => 'CORONA',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'USD',
                'descripcion' => 'DÓLAR',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'AED',
                'descripcion' => 'DIRHAM',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'HKD',
                'descripcion' => 'DÓLAR',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'INR',
                'descripcion' => 'RUPIA',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'MXN',
                'descripcion' => 'PESO',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'NOK',
                'descripcion' => 'CORONA',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'PYG',
                'descripcion' => 'GUARANI',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'PEN',
                'descripcion' => 'NUEVO SOL',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'GBP',
                'descripcion' => 'LIBRA',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'CNH',
                'descripcion' => 'YUAN RENMINBI OFFSHORE',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'SGD',
                'descripcion' => 'DÓLAR',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'SEK',
                'descripcion' => 'CORONA',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'CHF',
                'descripcion' => 'FRANCO',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'THB',
                'descripcion' => 'THAI BAHT',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'TWD',
                'descripcion' => 'DÓLAR',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'UYU',
                'descripcion' => 'PESO',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],
            [
                'codigo' => 'D.E.G',
                'descripcion' => 'DERECHO ESPECIAL DE GIRO',
                'nivel' => '0',
                'fk_id_parametrica' => '1',
            ],

            [
                'codigo' => 'PRIMER TRIMESTRE',
                'descripcion' => 'PERIODO',
                'nivel' => '0',
                'fk_id_parametrica' => '2',
            ],
            [
                'codigo' => 'SEGUNDO TRIMESTRE',
                'descripcion' => 'PERIODO',
                'nivel' => '0',
                'fk_id_parametrica' => '2',
            ],
            [
                'codigo' => 'TERCER TRIMESTRE',
                'descripcion' => 'PERIODO',
                'nivel' => '0',
                'fk_id_parametrica' => '2',
            ],
            [
                'codigo' => 'CUARTO TRIMESTRE',
                'descripcion' => 'PERIODO',
                'nivel' => '0',
                'fk_id_parametrica' => '2',
            ],

            [
                'codigo' => 'INVERSION',
                'descripcion' => 'FASE DEL PROYECTO',
                'nivel' => '0',
                'fk_id_parametrica' => '3',
            ],
            [
                'codigo' => 'PRE INVERSION',
                'descripcion' => 'FASE DEL PROYECTO',
                'nivel' => '0',
                'fk_id_parametrica' => '3',
            ],
            [
                'codigo' => 'NO APLICA',
                'descripcion' => 'FASE DEL PROYECTO',
                'nivel' => '0',
                'fk_id_parametrica' => '3',
            ],

            [
                'codigo' => 'CARRETERAS',
                'descripcion' => 'TIPO DE PROYECTO',
                'nivel' => '0',
                'fk_id_parametrica' => '4',
            ],
            [
                'codigo' => 'DOBLES VIAS',
                'descripcion' => 'TIPO DE PROYECTO',
                'nivel' => '0',
                'fk_id_parametrica' => '4',
            ],
            [
                'codigo' => 'PUENTES',
                'descripcion' => 'TIPO DE PROYECTO',
                'nivel' => '0',
                'fk_id_parametrica' => '4',
            ],
            [
                'codigo' => 'TUNELES',
                'descripcion' => 'TIPO DE PROYECTO',
                'nivel' => '0',
                'fk_id_parametrica' => '4',
            ],
            [
                'codigo' => 'CONSERVACION',
                'descripcion' => 'TIPO DE PROYECTO',
                'nivel' => '0',
                'fk_id_parametrica' => '4',
            ],
            [
                'codigo' => 'REHABILITACION',
                'descripcion' => 'TIPO DE PROYECTO',
                'nivel' => '0',
                'fk_id_parametrica' => '4',
            ],

            [
                'codigo' => 'TIERRA',
                'descripcion' => 'SUPERFICIE RODADURA',
                'nivel' => '0',
                'fk_id_parametrica' => '5',
            ],
            [
                'codigo' => 'EMPEDRADO',
                'descripcion' => 'SUPERFICIE RODADURA',
                'nivel' => '0',
                'fk_id_parametrica' => '5',
            ],
            [
                'codigo' => 'PAVIMENTO FLEXIBLE (ASFALTO)',
                'descripcion' => 'SUPERFICIE RODADURA',
                'nivel' => '0',
                'fk_id_parametrica' => '5',
            ],
            [
                'codigo' => 'PAVIMENTO RIGIDO (HORMIGON)',
                'descripcion' => 'SUPERFICIE RODADURA',
                'nivel' => '0',
                'fk_id_parametrica' => '5',
            ],
            [
                'codigo' => 'RIPIO',
                'descripcion' => 'SUPERFICIE RODADURA',
                'nivel' => '0',
                'fk_id_parametrica' => '5',
            ],
            [
                'codigo' => 'TRATAMIENTO SUPERFICIE',
                'descripcion' => 'SUPERFICIE RODADURA',
                'nivel' => '0',
                'fk_id_parametrica' => '5',
            ],
            [
                'codigo' => 'PAVIMENTO - RIPIO',
                'descripcion' => 'SUPERFICIE RODADURA',
                'nivel' => '0',
                'fk_id_parametrica' => '5',
            ],
            [
                'codigo' => 'PAVIMENTO',
                'descripcion' => 'SUPERFICIE RODADURA',
                'nivel' => '0',
                'fk_id_parametrica' => '5',
            ],
            [
                'codigo' => 'PAVIMENTO - TIERRA',
                'descripcion' => 'SUPERFICIE RODADURA',
                'nivel' => '0',
                'fk_id_parametrica' => '5',
            ],
            [
                'codigo' => 'RIPIO - TIERRA',
                'descripcion' => 'SUPERFICIE RODADURA',
                'nivel' => '0',
                'fk_id_parametrica' => '5',
            ],
            [
                'codigo' => 'ASFALTO',
                'descripcion' => 'SUPERFICIE RODADURA',
                'nivel' => '0',
                'fk_id_parametrica' => '5',
            ],
            [
                'codigo' => 'NO APLICA',
                'descripcion' => 'SUPERFICIE RODADURA',
                'nivel' => '0',
                'fk_id_parametrica' => '5',
            ],

            [
                'codigo' => 'EN EJECUCION',
                'descripcion' => 'SUPERFICIE RODADURA',
                'nivel' => '0',
                'fk_id_parametrica' => '6',
            ],
            [
                'codigo' => 'NUEVO / EN LICITACION',
                'descripcion' => 'SUPERFICIE RODADURA',
                'nivel' => '0',
                'fk_id_parametrica' => '6',
            ],
            [
                'codigo' => 'RESCINDIDO / EN LICITACION',
                'descripcion' => 'SUPERFICIE RODADURA',
                'nivel' => '0',
                'fk_id_parametrica' => '6',
            ],
            [
                'codigo' => 'CONCLUIDO',
                'descripcion' => 'SUPERFICIE RODADURA',
                'nivel' => '0',
                'fk_id_parametrica' => '6',
            ],


            [
                'codigo' => 'LICITACIÓN PÚBLICA',
                'descripcion' => 'MODALIDAD CONTRATACION',
                'nivel' => '0',
                'fk_id_parametrica' => '7',
            ],
            [
                'codigo' => 'ANPE',
                'descripcion' => 'MODALIDAD CONTRATACION',
                'nivel' => '0',
                'fk_id_parametrica' => '7',
            ],
            [
                'codigo' => 'MENOR',
                'descripcion' => 'MODALIDAD CONTRATACION',
                'nivel' => '0',
                'fk_id_parametrica' => '7',
            ],
            [
                'codigo' => 'DIRECTA',
                'descripcion' => 'MODALIDAD CONTRATACION',
                'nivel' => '0',
                'fk_id_parametrica' => '7',
            ],
            [
                'codigo' => 'EXECPCIÓN',
                'descripcion' => 'MODALIDAD CONTRATACION',
                'nivel' => '0',
                'fk_id_parametrica' => '7',
            ],
            [
                'codigo' => 'OTRAS MODALIDADES',
                'descripcion' => 'MODALIDAD CONTRATACION',
                'nivel' => '0',
                'fk_id_parametrica' => '7',
            ],
            [
                'codigo' => 'NO APLICA',
                'descripcion' => 'MODALIDAD CONTRATACION',
                'nivel' => '0',
                'fk_id_parametrica' => '7',
            ],


            [
                'codigo' => 'ENERO',
                'descripcion' => 'MES',
                'nivel' => '0',
                'fk_id_parametrica' => '8',
            ],
            [
                'codigo' => 'FEBRERO',
                'descripcion' => 'MES',
                'nivel' => '0',
                'fk_id_parametrica' => '8',
            ],
            [
                'codigo' => 'MARZO',
                'descripcion' => 'MES',
                'nivel' => '0',
                'fk_id_parametrica' => '8',
            ],
            [
                'codigo' => 'ABRIL',
                'descripcion' => 'MES',
                'nivel' => '0',
                'fk_id_parametrica' => '8',
            ],
            [
                'codigo' => 'MAYO',
                'descripcion' => 'MES',
                'nivel' => '0',
                'fk_id_parametrica' => '8',
            ],
            [
                'codigo' => 'JUNIO',
                'descripcion' => 'MES',
                'nivel' => '0',
                'fk_id_parametrica' => '8',
            ],
            [
                'codigo' => 'JULIO',
                'descripcion' => 'MES',
                'nivel' => '0',
                'fk_id_parametrica' => '8',
            ],
            [
                'codigo' => 'AGOSTO',
                'descripcion' => 'MES',
                'nivel' => '0',
                'fk_id_parametrica' => '8',
            ],
            [
                'codigo' => 'SEPTIEMBRE',
                'descripcion' => 'MES',
                'nivel' => '0',
                'fk_id_parametrica' => '8',
            ],
            [
                'codigo' => 'OCTUBRE',
                'descripcion' => 'MES',
                'nivel' => '0',
                'fk_id_parametrica' => '8',
            ],
            [
                'codigo' => 'NOVIEMBRE',
                'descripcion' => 'MES',
                'nivel' => '0',
                'fk_id_parametrica' => '8',
            ],
            [
                'codigo' => 'DICIEMBRE',
                'descripcion' => 'MES',
                'nivel' => '0',
                'fk_id_parametrica' => '8',
            ],

            [
                'codigo' => 'FORMULARIO 130',
                'descripcion' => 'TIPOS FORMULARIO POA',
                'nivel' => '0',
                'fk_id_parametrica' => '9',
            ],
            [
                'codigo' => 'FORMULARIO 190',
                'descripcion' => 'TIPOS FORMULARIO POA',
                'nivel' => '0',
                'fk_id_parametrica' => '9',
            ],
            [
                'codigo' => 'FORMULARIO 191-A',
                'descripcion' => 'TIPOS FORMULARIO POA',
                'nivel' => '0',
                'fk_id_parametrica' => '9',
            ],
            [
                'codigo' => 'FORMULARIO 192',
                'descripcion' => 'TIPOS FORMULARIO POA',
                'nivel' => '0',
                'fk_id_parametrica' => '9',
            ],
            [
                'codigo' => 'FORMULARIO 120',
                'descripcion' => 'TIPOS FORMULARIO POA',
                'nivel' => '0',
                'fk_id_parametrica' => '9',
            ],
            [
                'codigo' => 'FORMULARIO 121',
                'descripcion' => 'TIPOS FORMULARIO POA',
                'nivel' => '0',
                'fk_id_parametrica' => '9',
            ],
            [
                'codigo' => 'FORMULARIO 140',
                'descripcion' => 'TIPOS FORMULARIO POA',
                'nivel' => '0',
                'fk_id_parametrica' => '9',
            ],
            [
                'codigo' => 'FORMULARIO 150',
                'descripcion' => 'TIPOS FORMULARIO POA',
                'nivel' => '0',
                'fk_id_parametrica' => '9',
            ],
            [
                'codigo' => 'FORMULARIO 160',
                'descripcion' => 'TIPOS FORMULARIO POA',
                'nivel' => '0',
                'fk_id_parametrica' => '9',
            ],
            [
                'codigo' => 'FORMULARIO 170',
                'descripcion' => 'TIPOS FORMULARIO POA',
                'nivel' => '0',
                'fk_id_parametrica' => '9',
            ],
            [
                'codigo' => 'FORMULARIO 171',
                'descripcion' => 'TIPOS FORMULARIO POA',
                'nivel' => '0',
                'fk_id_parametrica' => '9',
            ],
            [
                'codigo' => 'FORMULARIO 193',
                'descripcion' => 'TIPOS FORMULARIO POA',
                'nivel' => '0',
                'fk_id_parametrica' => '9',
            ],

            [
                'codigo' => 'FORMULADO',
                'descripcion' => 'ESTADO POA',
                'nivel' => '0',
                'fk_id_parametrica' => '10',
            ],
            [
                'codigo' => 'REFORMULADO',
                'descripcion' => 'ESTADO POA',
                'nivel' => '0',
                'fk_id_parametrica' => '10',
            ],
            [
                'codigo' => 'ADICION',
                'descripcion' => 'ESTADO POA',
                'nivel' => '0',
                'fk_id_parametrica' => '10',
            ],
            [
                'codigo' => 'SEGUIMIENTO',
                'descripcion' => 'ESTADO POA',
                'nivel' => '0',
                'fk_id_parametrica' => '10',
            ],
            [
                'codigo' => 'PROGRAMADO',
                'descripcion' => 'ESTADO POA',
                'nivel' => '0',
                'fk_id_parametrica' => '10',
            ],
            [
                'codigo' => 'REPROGRAMADO',
                'descripcion' => 'ESTADO POA',
                'nivel' => '0',
                'fk_id_parametrica' => '10',
            ],

            [
                'codigo' => 'NO CORRESPONDE',
                'descripcion' => 'NO CORRESPONDE',
                'nivel' => '0',
                'fk_id_parametrica' => '11',
            ],

            [
                'codigo' => '2014',
                'descripcion' => 'GESTIONES',
                'nivel' => '0',
                'fk_id_parametrica' => '12',
            ],
            [
                'codigo' => '2015',
                'descripcion' => 'GESTIONES',
                'nivel' => '0',
                'fk_id_parametrica' => '12',
            ],
            [
                'codigo' => '2016',
                'descripcion' => 'GESTIONES',
                'nivel' => '0',
                'fk_id_parametrica' => '12',
            ],
            [
                'codigo' => '2017',
                'descripcion' => 'GESTIONES',
                'nivel' => '0',
                'fk_id_parametrica' => '12',
            ],
            [
                'codigo' => '2018',
                'descripcion' => 'GESTIONES',
                'nivel' => '0',
                'fk_id_parametrica' => '12',
            ],
            [
                'codigo' => '2019',
                'descripcion' => 'GESTIONES',
                'nivel' => '0',
                'fk_id_parametrica' => '12',
            ],
            [
                'codigo' => '2020',
                'descripcion' => 'GESTIONES',
                'nivel' => '0',
                'fk_id_parametrica' => '12',
            ],
            [
                'codigo' => '2021',
                'descripcion' => 'GESTIONES',
                'nivel' => '0',
                'fk_id_parametrica' => '12',
            ],
            [
                'codigo' => '2022',
                'descripcion' => 'GESTIONES',
                'nivel' => '0',
                'fk_id_parametrica' => '12',
            ],
            [
                'codigo' => '2023',
                'descripcion' => 'GESTIONES',
                'nivel' => '0',
                'fk_id_parametrica' => '12',
            ],
            [
                'codigo' => '2024',
                'descripcion' => 'GESTIONES',
                'nivel' => '0',
                'fk_id_parametrica' => '12',
            ],
            [
                'codigo' => '2025',
                'descripcion' => 'GESTIONES',
                'nivel' => '0',
                'fk_id_parametrica' => '12',
            ],
            [
                'codigo' => '2026',
                'descripcion' => 'GESTIONES',
                'nivel' => '0',
                'fk_id_parametrica' => '12',
            ],
            [
                'codigo' => '2027',
                'descripcion' => 'GESTIONES',
                'nivel' => '0',
                'fk_id_parametrica' => '12',
            ],
            [
                'codigo' => '2028',
                'descripcion' => 'GESTIONES',
                'nivel' => '0',
                'fk_id_parametrica' => '12',
            ],
            [
                'codigo' => '2029',
                'descripcion' => 'GESTIONES',
                'nivel' => '0',
                'fk_id_parametrica' => '12',
            ],
            [
                'codigo' => '2030',
                'descripcion' => 'GESTIONES',
                'nivel' => '0',
                'fk_id_parametrica' => '12',
            ],

            [
                'codigo' => 'CONSULTORÍA',
                'descripcion' => 'TIPO DE FUNCIONAMIENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '13',
            ],
            [
                'codigo' => 'BIENES MATERIALES',
                'descripcion' => 'TIPO DE FUNCIONAMIENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '13',
            ],
            [
                'codigo' => 'SERVICIO',
                'descripcion' => 'TIPO DE FUNCIONAMIENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '13',
            ],
            [
                'codigo' => 'ACTIVOS FIJOS',
                'descripcion' => 'TIPO DE FUNCIONAMIENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '13',
            ],
            [
                'codigo' => 'OPERACIONES',
                'descripcion' => 'TIPO DE FUNCIONAMIENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '13',
            ],

            [
                'codigo' => 'CONSULTORIA INDIVIDUAL DE LINEA',
                'descripcion' => 'TIPO CONSULTORIA',
                'nivel' => '0',
                'fk_id_parametrica' => '14',
            ],
            [
                'codigo' => 'POR PRODUCTO',
                'descripcion' => 'TIPO CONSULTORIA',
                'nivel' => '0',
                'fk_id_parametrica' => '14',
            ],
            [
                'codigo' => 'AUDITORIA EXTERNA',
                'descripcion' => 'TIPO DE FUNCIONAMIENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '14',
            ],
            [
                'codigo' => 'OTROS',
                'descripcion' => 'MODALIDAD DE CONTRATACION',
                'nivel' => '0',
                'fk_id_parametrica' => '14',
            ],
            [
                'codigo' => 'FISCALIZACION',
                'descripcion' => 'MODALIDAD DE CONTRATACION',
                'nivel' => '0',
                'fk_id_parametrica' => '14',
            ],


            [
                'codigo' => 'PIEZA',
                'descripcion' => 'UNIDAD DE MEDIDA',
                'nivel' => '0',
                'fk_id_parametrica' => '15',
            ],
            [
                'codigo' => 'PAQUETE',
                'descripcion' => 'UNIDAD DE MEDIDA',
                'nivel' => '0',
                'fk_id_parametrica' => '15',
            ],
            [
                'codigo' => 'CAJA',
                'descripcion' => 'UNIDAD DE MEDIDA',
                'nivel' => '0',
                'fk_id_parametrica' => '15',
            ],
            [
                'codigo' => 'LIBRO',
                'descripcion' => 'UNIDAD DE MEDIDA',
                'nivel' => '0',
                'fk_id_parametrica' => '15',
            ],
            [
                'codigo' => 'KILO',
                'descripcion' => 'UNIDAD DE MEDIDA',
                'nivel' => '0',
                'fk_id_parametrica' => '15',
            ],

            [
                'codigo' => 'COMPONENTE',
                'descripcion' => 'TIPO COMPONENTE',
                'nivel' => '0',
                'fk_id_parametrica' => '16',
            ],
            [
                'codigo' => 'SUBCOMPONENTE',
                'descripcion' => 'TIPO COMPONENTE',
                'nivel' => '0',
                'fk_id_parametrica' => '16',
            ],

            [
                'codigo' => 'CHUQUISACA',
                'descripcion' => 'DEPARTAMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '17',
            ],
            [
                'codigo' => 'LA PAZ',
                'descripcion' => 'DEPARTAMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '17',
            ],
            [
                'codigo' => 'COCHABAMBA',
                'descripcion' => 'DEPARTAMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '17',
            ],
            [
                'codigo' => 'ORURO',
                'descripcion' => 'DEPARTAMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '17',
            ],
            [
                'codigo' => 'POTOSI',
                'descripcion' => 'DEPARTAMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '17',
            ],
            [
                'codigo' => 'TARIJA',
                'descripcion' => 'DEPARTAMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '17',
            ],
            [
                'codigo' => 'SANTA CRUZ',
                'descripcion' => 'DEPARTAMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '17',
            ],
            [
                'codigo' => 'BENI',
                'descripcion' => 'DEPARTAMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '17',
            ],
            [
                'codigo' => 'PANDO',
                'descripcion' => 'DEPARTAMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '17',
            ],


            [
                'codigo' => 'EJE DE INTEGRACION SUR',
                'descripcion' => 'EJE DE INTEGRACION',
                'nivel' => '0',
                'fk_id_parametrica' => '18',
            ],
            [
                'codigo' => 'NINGUNO',
                'descripcion' => 'EJE DE INTEGRACION',
                'nivel' => '0',
                'fk_id_parametrica' => '18',
            ],
            [
                'codigo' => 'EJE DE INTEGRACION NORTE',
                'descripcion' => 'EJE DE INTEGRACION',
                'nivel' => '0',
                'fk_id_parametrica' => '18',
            ],
            [
                'codigo' => 'EJE DE INTEGRACION ESTE OESTE',
                'descripcion' => 'EJE DE INTEGRACION',
                'nivel' => '0',
                'fk_id_parametrica' => '18',
            ],

            [
                'codigo' => 'CORREDOR 1/ESTE OESTE',
                'descripcion' => 'CORREDOR',
                'nivel' => '0',
                'fk_id_parametrica' => '19',
            ],
            [
                'codigo' => 'CORREDOR 2/NORTE SUR',
                'descripcion' => 'CORREDOR',
                'nivel' => '0',
                'fk_id_parametrica' => '19',
            ],
            [
                'codigo' => 'CORREDOR 3/OESTE NORTE',
                'descripcion' => 'CORREDOR',
                'nivel' => '0',
                'fk_id_parametrica' => '19',
            ],
            [
                'codigo' => 'CORREDOR 4/OESTE SUR',
                'descripcion' => 'CORREDOR',
                'nivel' => '0',
                'fk_id_parametrica' => '19',
            ],
            [
                'codigo' => 'CORREDOR 5/CENTRAL SUR',
                'descripcion' => 'CORREDOR',
                'nivel' => '0',
                'fk_id_parametrica' => '19',
            ],
            [
                'codigo' => 'NINGUNO',
                'descripcion' => 'CORREDOR',
                'nivel' => '0',
                'fk_id_parametrica' => '19',
            ],
            [
                'codigo' => 'DIAGONAL JAIME MENDOZA',
                'descripcion' => 'CORREDOR',
                'nivel' => '0',
                'fk_id_parametrica' => '19',
            ],

            [
                'codigo' => 'NUEVO',
                'descripcion' => 'ESTADO REGISTRO',
                'nivel' => '0',
                'fk_id_parametrica' => '20',
            ],
            [
                'codigo' => 'INACTIVO',
                'descripcion' => 'CORREDOR',
                'nivel' => '0',
                'fk_id_parametrica' => '20',
            ],


            [
                'codigo' => 'EJECUCION',
                'descripcion' => 'ESTADO CONTRATACION',
                'nivel' => '0',
                'fk_id_parametrica' => '21',
            ],
            [
                'codigo' => 'NUEVO',
                'descripcion' => 'ESTADO CONTRATACION',
                'nivel' => '0',
                'fk_id_parametrica' => '21',
            ],


            [
                'codigo' => 'NUEVO',
                'descripcion' => 'ESTADO CONTRATACION',
                'nivel' => '0',
                'fk_id_parametrica' => '21',
            ],


            [
                'codigo' => 'PROGRAMACION',
                'descripcion' => 'TIPO PROGRAMACION INVERSION',
                'nivel' => '0',
                'fk_id_parametrica' => '23',
            ],
            [
                'codigo' => 'SEGUIMIENTO',
                'descripcion' => 'TIPO PROGRAMACION INVERSION',
                'nivel' => '0',
                'fk_id_parametrica' => '23',
            ],

            [
                'codigo' => 'PRIORIDAD A',
                'descripcion' => 'PRIORIDAD A',
                'nivel' => '0',
                'fk_id_parametrica' => '24',
            ],
            [
                'codigo' => 'PRIORIDAD B',
                'descripcion' => 'PRIORIDAD B',
                'nivel' => '0',
                'fk_id_parametrica' => '24',
            ],
            [
                'codigo' => 'PRIORIDAD C',
                'descripcion' => 'PRIORIDAD C',
                'nivel' => '0',
                'fk_id_parametrica' => '24',
            ],
            [
                'codigo' => 'PRIORIDAD D',
                'descripcion' => 'PRIORIDAD D',
                'nivel' => '0',
                'fk_id_parametrica' => '24',
            ],
            [
                'codigo' => 'PRIORIDAD E',
                'descripcion' => 'PRIORIDAD E',
                'nivel' => '0',
                'fk_id_parametrica' => '24',
            ],


            [
                'codigo' => 'CONTRATO DE PRESTAMO',
                'descripcion' => 'CONTRATO DE PRESTAMO',
                'nivel' => '0',
                'fk_id_parametrica' => '25',
            ],
            [
                'codigo' => 'CARTA ACUERDO',
                'descripcion' => 'CARTA ACUERDO',
                'nivel' => '0',
                'fk_id_parametrica' => '25',
            ],
            [
                'codigo' => 'CIF',
                'descripcion' => 'CIF',
                'nivel' => '0',
                'fk_id_parametrica' => '25',
            ],
            [
                'codigo' => 'CONVENIO DE FINANCIAMIENTO',
                'descripcion' => 'CONVENIO DE FINANCIAMIENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '25',
            ],
            [
                'codigo' => 'CONVENIO DE PRESTAMO',
                'descripcion' => 'CONVENIO DE PRESTAMO',
                'nivel' => '0',
                'fk_id_parametrica' => '25',
            ],


            [
                'codigo' => 'FORMULACION',
                'descripcion' => 'ETAPA POA',
                'nivel' => '0',
                'fk_id_parametrica' => '26',
            ],
            [
                'codigo' => 'REFORMULADO',
                'descripcion' => 'ETAPA POA',
                'nivel' => '0',
                'fk_id_parametrica' => '26',
            ],
            [
                'codigo' => 'ADICIONES',
                'descripcion' => 'ETAPA POA',
                'nivel' => '0',
                'fk_id_parametrica' => '26',
            ],


            [
                'codigo' => 'HABILITAR',
                'descripcion' => 'POA',
                'nivel' => '0',
                'fk_id_parametrica' => '27',
            ],
            [
                'codigo' => 'CERRAR',
                'descripcion' => 'POA',
                'nivel' => '0',
                'fk_id_parametrica' => '27',
            ],

            [
                'codigo' => 'JUSTIFICACION DE GASTO',
                'descripcion' => 'TIPO DE DOCUMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '28',
            ],
            [
                'codigo' => 'ESTADOS DE INVERSION DE LOS CONTRATOS DE PRESTAMO',
                'descripcion' => 'TIPO DE DOCUMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '28',
            ],
            [
                'codigo' => 'BASE DE DATOS DE FECHAS DE ULTIMO DESEMBOLSO',
                'descripcion' => 'TIPO DE DOCUMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '28',
            ],
            [
                'codigo' => 'AMPLIACION DE PLAZO DE ULTIMO DESEMBOLSO',
                'descripcion' => 'TIPO DE DOCUMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '28',
            ],
            [
                'codigo' => 'SOLICITUD DE DISPENSA',
                'descripcion' => 'TIPO DE DOCUMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '28',
            ],
            [
                'codigo' => 'SOLICITUD DE DESEMBOLSO',
                'descripcion' => 'TIPO DE DOCUMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '28',
            ],
            [
                'codigo' => 'CAMBIOS DE ESTRUCTURA DE FINANCIAMIENTO',
                'descripcion' => 'TIPO DE DOCUMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '28',
            ],
            [
                'codigo' => 'DOCUMENTOS PARA APROBACION DE CONTRATO DE PRÉSTAMO',
                'descripcion' => 'TIPO DE DOCUMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '28',
            ],
            [
                'codigo' => 'ORDEN DE CAMBIO',
                'descripcion' => 'TIPO DE DOCUMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '28',
            ],
            [
                'codigo' => 'CONTRATOS MODIFICATORIOS',
                'descripcion' => 'TIPO DE DOCUMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '28',
            ],
            [
                'codigo' => 'SOLICITUD DE CONFORMIDAD (NO OBJECIÓN)',
                'descripcion' => 'TIPO DE DOCUMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '28',
            ],
            [
                'codigo' => 'REVISIÓN DE CARTERA',
                'descripcion' => 'TIPO DE DOCUMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '28',
            ],
            [
                'codigo' => 'REMISIÓN DE AYUDA MEMORIAS',
                'descripcion' => 'TIPO DE DOCUMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '28',
            ],
            [
                'codigo' => 'REMISIÓN DE INFORMES SEMESTRALES',
                'descripcion' => 'TIPO DE DOCUMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '28',
            ],
            [
                'codigo' => 'REMISIÓN DE INFORMES TRIMESTRALES',
                'descripcion' => 'TIPO DE DOCUMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '28',
            ],
            [
                'codigo' => 'AMPLIACIÓN DE PLAZO DE PRIMER DESEMBOLSO',
                'descripcion' => 'TIPO DE DOCUMENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '28',
            ],
            [
                'codigo' => 'CONTRATO DE PRESTAMO',
                'descripcion' => 'CONTRATO DE PRESTAMO',
                'nivel' => '0',
                'fk_id_parametrica' => '28',
            ],
            [
                'codigo' => 'CONVENIO DE PRESTAMO',
                'descripcion' => 'CONVENIO DE PRESTAMO',
                'nivel' => '0',
                'fk_id_parametrica' => '28',
            ],
            [
                'codigo' => 'CONVENIO DE FINANCIAMIENTO',
                'descripcion' => 'CONVENIO DE FINANCIAMIENTO',
                'nivel' => '0',
                'fk_id_parametrica' => '28',
            ],

            [
                'codigo' => 'APROBADO',
                'descripcion' => 'ESTADO FORMULARIO',
                'nivel' => '0',
                'fk_id_parametrica' => '29',
            ],
            [
                'codigo' => 'PENDIENTE',
                'descripcion' => 'ESTADO FORMULARIO',
                'nivel' => '0',
                'fk_id_parametrica' => '29',
            ],
            [
                'codigo' => 'RECHAZADO',
                'descripcion' => 'ESTADO FORMULARIO',
                'nivel' => '0',
                'fk_id_parametrica' => '29',
            ],


            [
                'codigo' => 'A PARTIR DE LA FECHA EN QUE SEGÚN NORMAS DEL ESTADO ADQUIERA PLENA VALIDEZ',
                'descripcion' => 'VIGENCIA',
                'nivel' => '0',
                'fk_id_parametrica' => '30',
            ],
            [
                'codigo' => 'A PARTIR DE LA SUSCRIPCIÓN  DEL CONTRATO',
                'descripcion' => 'VIGENCIA',
                'nivel' => '0',
                'fk_id_parametrica' => '30',
            ],
            [
                'codigo' => 'EN LA FECHA EN QUE EL BANCO SE DECLARE SATISFECHO CON LAS PRUEBAS QUE SOLICITA',
                'descripcion' => 'VIGENCIA',
                'nivel' => '0',
                'fk_id_parametrica' => '30',
            ],
            [
                'codigo' => 'A PARTIR DE LA FECHA DE NOTIFICACIÓN ENVIADA MEDIANTE NOTA AL ORGANISMO',
                'descripcion' => 'VIGENCIA',
                'nivel' => '0',
                'fk_id_parametrica' => '30',
            ],
            [
                'codigo' => 'A PARTIR DE LA EFECTIVIDAD DEL BANCO',
                'descripcion' => 'VIGENCIA',
                'nivel' => '0',
                'fk_id_parametrica' => '30',
            ],


            [
                'codigo' => 'ADMINISTRADOR GLOBAL',
                'descripcion' => 'ADMINISTRADOR GLOBAL',
                'nivel' => '0',
                'fk_id_parametrica' => '31',
            ],
            [
                'codigo' => 'ADMINISTRADOR DE MODULO',
                'descripcion' => 'ADMINISTRADOR DE MODULO',
                'nivel' => '0',
                'fk_id_parametrica' => '31',
            ],
            [
                'codigo' => 'APROBADO',
                'descripcion' => 'APROBADO',
                'nivel' => '0',
                'fk_id_parametrica' => '31',
            ],
            [
                'codigo' => 'ELABORADOR',
                'descripcion' => 'ELABORADOR',
                'nivel' => '0',
                'fk_id_parametrica' => '31',
            ],
            [
                'codigo' => 'VISTA',
                'descripcion' => 'VISTA',
                'nivel' => '0',
                'fk_id_parametrica' => '31',
            ],

            [
                'codigo' => '',
                'descripcion' => 'CUMPLIDO',
                'nivel' => '0',
                'fk_id_parametrica' => '32',
            ],
            [
                'codigo' => '',
                'descripcion' => 'NO CUMPLIDO',
                'nivel' => '0',
                'fk_id_parametrica' => '32',
            ],
            [
                'codigo' => '',
                'descripcion' => 'EN PLAZO',
                'nivel' => '0',
                'fk_id_parametrica' => '32',
            ],
            [
                'codigo' => '',
                'descripcion' => 'C-21',
                'nivel' => '0',
                'fk_id_parametrica' => '33',
            ],
            [
                'codigo' => '',
                'descripcion' => 'C-31',
                'nivel' => '0',
                'fk_id_parametrica' => '33',
            ],


            [
                'codigo' => 'PO',
                'descripcion' => 'PAGOS DIRECTOS',
                'nivel' => '0',
                'fk_id_parametrica' => '34',
            ],
            [
                'codigo' => 'CTA DESG',
                'descripcion' => 'ANTICIPO EM CUENTA DESIGNADA',
                'nivel' => '0',
                'fk_id_parametrica' => '34',
            ],
            [
                'codigo' => 'COM',
                'descripcion' => 'COMISION INICIAL',
                'nivel' => '0',
                'fk_id_parametrica' => '34',
            ],
            [
                'codigo' => 'IDV',
                'descripcion' => 'CUMPLIMIENTO A INDICADORES A.1',
                'nivel' => '0',
                'fk_id_parametrica' => '34',
            ],

            [
                'codigo' => '1001',
                'descripcion' => 'BANCO NACIONAL DE BOLIVIA S.A.',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1002',
                'descripcion' => 'BHN MULTIBANCO S.A.',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1003',
                'descripcion' => 'BANCO MERCANTIL SANTA CRUZ S.A.',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1004',
                'descripcion' => 'BANCO CENTRAL DE BOLIVIA',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1005',
                'descripcion' => 'BANCO DE CREDITO DE BOLIVIA S.A.',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1006',
                'descripcion' => 'BANCO BOLIVIANO AMERICANO S.A.',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1007',
                'descripcion' => 'BANCO DE LA NACION ARGENTIAN S.A.',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1008',
                'descripcion' => 'BANCO DO BRASIL S.A.',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1009',
                'descripcion' => 'BANCO BISA S.A.',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1010',
                'descripcion' => 'CITIBANK S.A.',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1011',
                'descripcion' => 'BANCO SANTA CRUZ S.A.',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1012',
                'descripcion' => 'BANCO DE LA PAZ S.A',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1013',
                'descripcion' => 'BANCO REAL S.A.',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1014',
                'descripcion' => 'BANCO UNION S.A.',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1015',
                'descripcion' => 'BANCO INTERNACIONAL DE DESARROLLO S.A.',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1016',
                'descripcion' => 'BANCO ECONOMICO S.A.',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1017',
                'descripcion' => 'BANCO SOLIDARIO S.A.',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1018',
                'descripcion' => 'BANCO GANADERO S.A.',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1019',
                'descripcion' => 'BANCO LATINOAMERICANO DE DESARROLLO',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1020',
                'descripcion' => 'BANCO DE LA VIVIENDA',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1021',
                'descripcion' => 'BANCO DE CREDITO ORURO',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1022',
                'descripcion' => 'BANCO DE POTOSO',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1023',
                'descripcion' => 'BANCO DEL PROGRESO',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1024',
                'descripcion' => 'BANCO AGRICOLA DE BOLIVIA',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1025',
                'descripcion' => 'BANCO DE FINANCIAMIENTO INDUSTRIAL',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1026',
                'descripcion' => 'BANCO MINERO DE BOLIVIA',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1028',
                'descripcion' => 'BANCO SUR',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1029',
                'descripcion' => 'BANCO DE COCHABAMBA',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1033',
                'descripcion' => 'BANCO FIE S.A.',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1034',
                'descripcion' => 'BANCO FORTALEZA S.A.',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '1990',
                'descripcion' => 'BANCO DE CREDITO PERU.',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '2001',
                'descripcion' => 'MUTUAL LA PRIMERA',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '2002',
                'descripcion' => 'MUTUAL LA PAZ',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '2003',
                'descripcion' => 'MUTUAL GUAPAY',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3000',
                'descripcion' => 'CITIBANK',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3001',
                'descripcion' => 'CONTINENTAL NATIONAL BANK',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3002',
                'descripcion' => 'SANTANDER RIO',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3003',
                'descripcion' => 'ITAÚ',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3004',
                'descripcion' => 'BANCO DE CREDITO PERU',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3005',
                'descripcion' => 'BANCO DE CREDITO E INVERSIONES DE CHILE',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3006',
                'descripcion' => 'STANFORD INTERNATIONAL BANK',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3007',
                'descripcion' => 'SANTANDER CENTRAL HISPANO DE MIAMI',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3008',
                'descripcion' => 'LLOYDS TSB BANK PLC',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3009',
                'descripcion' => 'SUNTRUST BANK',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3010',
                'descripcion' => 'HSBC',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3011',
                'descripcion' => 'STANDARD CHARTERED BANK',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3012',
                'descripcion' => 'CHASSE MANHATTAN BANK',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3013',
                'descripcion' => 'BANES NET',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3014',
                'descripcion' => 'BBVA',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3015',
                'descripcion' => 'BANCO POPULAR',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3016',
                'descripcion' => 'BANCO DE AMERICA',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3017',
                'descripcion' => 'BANCO LA CAIXA',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3018',
                'descripcion' => 'BANCO WELLS FARGO',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3019',
                'descripcion' => 'BANCO SANTANDER ESPAÑA',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3020',
                'descripcion' => 'CITY NATIONAL BANK',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3021',
                'descripcion' => 'FIRST AMERICAN BANK',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3022',
                'descripcion' => 'BANCO SANTANDER',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '3023',
                'descripcion' => 'BANCO INTERNACIONAL DEL PERÚ S.A. (INTERBANK)',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '5001',
                'descripcion' => 'CAJA LOS ANDES S.A. FFP',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '5005',
                'descripcion' => 'FONDO FIE FFP S.A.',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '5007',
                'descripcion' => 'PRODEM FFP S.A.',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '5008',
                'descripcion' => 'FORTALEZA FFP S.A.',
                'nivel' => '0',
                'fk_id_parametrica' => '35',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'NIT',
                'nivel' => '0',
                'fk_id_parametrica' => '36',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'CI',
                'nivel' => '0',
                'fk_id_parametrica' => '36',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'ENT',
                'nivel' => '0',
                'fk_id_parametrica' => '36',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'CON IMPUTACIÓN',
                'nivel' => '0',
                'fk_id_parametrica' => '37',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'SIN IMPUTACIÓN',
                'nivel' => '0',
                'fk_id_parametrica' => '37',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'CAMBIO DE IMPUTACIÓN',
                'nivel' => '0',
                'fk_id_parametrica' => '38',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'NORMAL',
                'nivel' => '0',
                'fk_id_parametrica' => '38',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'REVERSIÓN',
                'nivel' => '0',
                'fk_id_parametrica' => '38',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'BANCO',
                'nivel' => '0',
                'fk_id_parametrica' => '39',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'COMPENSACIÓN',
                'nivel' => '0',
                'fk_id_parametrica' => '39',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'EFECTIVO',
                'nivel' => '0',
                'fk_id_parametrica' => '39',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'ESPECIE',
                'nivel' => '0',
                'fk_id_parametrica' => '39',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'VALORES',
                'nivel' => '0',
                'fk_id_parametrica' => '39',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'OTROS',
                'nivel' => '0',
                'fk_id_parametrica' => '40',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'DOCUMENTO DE REGULARIZACIÓN',
                'nivel' => '0',
                'fk_id_parametrica' => '40',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'EXTRACTO BANCARIO',
                'nivel' => '0',
                'fk_id_parametrica' => '40',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'BOLETA DE DEPOSITO',
                'nivel' => '0',
                'fk_id_parametrica' => '40',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'CRÉDITO AJUSTE EN TESORERÍA',
                'nivel' => '0',
                'fk_id_parametrica' => '40',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'C-21 SIP',
                'nivel' => '0',
                'fk_id_parametrica' => '40',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'MEDIO DE PAGO DOCUMENTO DE EJECUCUIÓN',
                'nivel' => '0',
                'fk_id_parametrica' => '40',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'EXTRACTO BANCARIO RUL',
                'nivel' => '0',
                'fk_id_parametrica' => '40',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'CON MOVIMIENTO DE FONDOS',
                'nivel' => '0',
                'fk_id_parametrica' => '41',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'SIN MOVIMIENTO DE FONDOS',
                'nivel' => '0',
                'fk_id_parametrica' => '41',
            ],


            [
                'codigo' => 'PID',
                'descripcion' => 'PAGO INDIRECTO',
                'nivel' => '0',
                'fk_id_parametrica' => '42',
            ],
            [
                'codigo' => 'PD',
                'descripcion' => 'PAGO DIRECTO',
                'nivel' => '0',
                'fk_id_parametrica' => '42',
            ],
            [
                'codigo' => 'O',
                'descripcion' => 'ORIGINAL',
                'nivel' => '0',
                'fk_id_parametrica' => '43',
            ],
            [
                'codigo' => 'M',
                'descripcion' => 'MODIFICATORIO',
                'nivel' => '0',
                'fk_id_parametrica' => '43',
            ],
            [
                'codigo' => 'OC',
                'descripcion' => 'ORDEN DE CAMBIO',
                'nivel' => '0',
                'fk_id_parametrica' => '43',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'A PARTIR DE LA FIRMA DE CONTRATO',
                'nivel' => '0',
                'fk_id_parametrica' => '44',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'A PARTIR DEL DIA SIGUIENTE HABIL DE LA FIRMA DEL CONTRATO',
                'nivel' => '0',
                'fk_id_parametrica' => '44',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'A PARTIR DE LA ORDEN DE PROCEDER',
                'nivel' => '0',
                'fk_id_parametrica' => '44',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'CONTRATO ORIGINAL',
                'nivel' => '0',
                'fk_id_parametrica' => '45',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'CONTRATO MODIFICATORIO',
                'nivel' => '0',
                'fk_id_parametrica' => '45',
            ],
            [
                'codigo' => '-',
                'descripcion' => 'ORDEN DE CAMBIO',
                'nivel' => '0',
                'fk_id_parametrica' => '45',
            ],
            [
                'codigo' => 'ADM',
                'descripcion' => 'ADMINISTRADOR CENTRAL',
                'nivel' => '1',
                'fk_id_parametrica' => '46',
            ],
            [
                'codigo' => 'PRE',
                'descripcion' => 'PRESUPUESTOS',
                'nivel' => '2',
                'fk_id_parametrica' => '46',
            ],
            [
                'codigo' => 'TES',
                'descripcion' => 'TESORERIA',
                'nivel' => '3',
                'fk_id_parametrica' => '46',
            ],
            [
                'codigo' => 'CONT',
                'descripcion' => 'CONTABILIDAD',
                'nivel' => '4',
                'fk_id_parametrica' => '46',
            ],

        ]);
    }
}
